PIW/urls.py
from django.contrib import admin
from django.urls import path, include
from lab1 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('lab1/', include("lab1.urls")),
    path('lab2/', include("lab2.urls")),
    path('lab3/', include("lab3.urls")),
    path('lab4/', include("lab4.urls"))
]

lab1/urls.py
from django.urls import path, include
from . import views

app_name = "lab1"

urlpatterns = [
    path('game/', views.game, name="game"),
    path('main/', views.main, name="main"),
    path('register/', views.register, name="register"),
    path('sign/', views.sign, name="sign"),

]

lab2/urls.py
from django.urls import path, include
from . import views

app_name = "lab2"

urlpatterns = [
    path('form/', views.form, name="form"),
    path('quadratic/', views.quadratic, name="quadratic"),
    path('picture/', views.picture, name="picture"),
    path('animals/', views.animals, name="animals"),
    path('animation/', views.animation, name="animation"),
    path('game/', views.game, name="game"),

]

lab3/urls.py
from django.urls import path, include
from . import views

app_name = "lab3"

urlpatterns = [
    path('canvas/', views.canvas, name="canvas"),
    path('snake/', views.snake, name="snake"),
    path('scores/', views.scores, name="scores"),

]

lab4/urls.py
from django.urls import path, include
from . import views

app_name = "lab4"

urlpatterns = [
    path('queue/', views.queue, name="queue"),

]

lab4/models.py
from django.db import models

# Create your models here.

lab1/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "index.html", context=None)

def main(request):
    return render(request, "lab1/main.html", context=None)

def game(request):
    return render(request, "lab1/game.html", context=None)

def register(request):
    return render(request, "lab1/register.html", context=None)

def sign(request):
    return render(request, "lab1/sign.html", context=None)

lab2/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, "lab2/index.html", context=None)

def form(request):
    return render(request, "lab2/form.html", context=None)

def quadratic(request):
    return render(request, "lab2/quadratic.html", context=None)

def picture(request):
    return render(request, "lab2/picture.html", context=None)

def animals(request):
    return render(request, "lab2/animals.html", context=None)

def animation(request):
    return render(request, "lab2/animation.html", context=None)

def animation(request):
    return render(request, "lab2/animation.html", context=None)

def game(request):
    return render(request, "lab2/game.html", context=None)

lab3/views.py
from django.shortcuts import render


# Create your views here.

def canvas(request):
    return render(request, "lab3/canvas.html", context=None)


def snake(request):
    return render(request, "lab3/snake.html", context=None)


def scores(request):
    return render(request, "lab3/scores.html", context=None)

lab4/views.py
from django.shortcuts import render

# Create your views here.

def queue(request):
    return render(request, "lab4/queue.html")

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title_block %}

    {% endblock %}
    <link rel="stylesheet" href="{% static 'libraries/bootstrap.css' %}">

    <script src="{% static 'libraries/jquery.js' %}"></script>
    <script src="{% static 'libraries/poper.js' %}"></script>
    <script src="{% static 'libraries/bootstrap_js.js' %}"></script>

    {% block css_block %}
    {% endblock css_block %}
</head>

<style>
    .dropdown-menu {
        background-color: #343a40;
    }

    .dropdown-item {
        color: white;
    }
</style>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">#PIW</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Laboratorium 1
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url "lab1:main" %}">Strona główna</a>
                    <a class="dropdown-item" href="{% url "lab1:register" %}">Rejestracja</a>
                    <a class="dropdown-item" href="{% url "lab1:sign" %}">Logowanie</a>
                    <a class="dropdown-item" href="{% url "lab1:game" %}">Mini-Gra</a>
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Laboratorium 2
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url "lab2:form" %}">Zadanie 1</a>
                    <a class="dropdown-item" href="{% url "lab2:quadratic" %}">Zadanie 2</a>
                    <a class="dropdown-item" href="{% url "lab2:picture" %}">Zadanie 3</a>
                    <a class="dropdown-item" href="{% url "lab2:animals" %}">Zadanie 4</a>
                    <a class="dropdown-item" href="{% url "lab2:animation" %}">Zadanie 5</a>
                    <a class="dropdown-item" href="{% url "lab2:game" %}">Zadanie 6</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Laboratorium 3
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url "lab3:canvas" %}">Zadanie 1</a>
                    <a class="dropdown-item" href="{% url "lab3:snake" %}">Zadanie 2</a>
                    <a class="dropdown-item" href="{% url "lab3:scores" %}">Zadanie 3</a>
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Laboratorium 4
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url "lab4:queue" %}">Zadanie 1</a>
{#                    <a class="dropdown-item" href="{% url "lab3:snake" %}">Zadanie 2</a>#}
{#                    <a class="dropdown-item" href="{% url "lab3:scores" %}">Zadanie 3</a>#}
                </div>
            </li>
        </ul>
    </div>
</nav>
{% block body_block %}
{% endblock body_block %}
</body>
</html>

{% block script %}
{% endblock script %}

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block css_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
{% endblock css_block %}

{% block body_block %}
    <br>
    <div class="container">
        <div class="jumbotron">
            <h1>Projektowanie Interfejsów Webowych</h1>
        </div>
    </div>
{% endblock body_block %}

templates/lab1/game.html
{% extends "base.html" %}
{% load static %}

{% block title_block %}
    <title>Kółko i krzyżyk</title>
{% endblock %}

{% block css_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/ticktoe.css' %}">
{% endblock css_block %}


{% block body_block %}
    <div class="container">
        <div class="jumbotron j1">
            <h1 class="display-4"><strong>Kółko i krzyżyk</strong></h1>
            <p class="lead">Prosta mini gra nie zawierająca systemu spawdzania rezultatów</p>
            <button id="but" type="button" class="btn btn-primary">Restart!</button>
        </div>

        <table class="myTable">
            <tbody>
            <tr>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            </tbody>
        </table>
    </div>
{% endblock %}
{% block script %}
    <script src="{% static "js/tick.js" %}"></script>
{% endblock %}

templates/lab1/main.html
{% extends "base.html" %}
{% load static %}

{% block title_block %}
    <title>Strona główna</title>
{% endblock %}

{% block css_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/master.css' %}">
{% endblock css_block %}


{% block body_block %}
    <br>
    <div class="container">
        <div class="jumbotron j2">
            <h1 class="display-4"> Strona główna </h1>

            <p class="lead">Pierwsze laboratorium Projektowania Interfejsów Webowych</p>


            <ol>
                <li>Celem laboratorium jest utworzenie prostego portalu WWW</li>
                <li>Portal WWW zawiera menu, teksty i elementy graficzne</li>
                <li>Zawarte strony:</li>
                <ul>
                    <li><a href="main.html">Strona główna</a></li>
                    <li><a href="register.html">Rejestracja</a></li>
                    <li><a href="sign.html">Logowanie</a></li>
                    <li><a href="game.html">Mini-gra</a></li>
                    <li><a href="https://getbootstrap.com/">Bootstrap</a></li>
                </ul>
                <li>Odnośniki do zdjęć wykorzystanych poniżej</li>
                <ul>
                    <li><a href="https://d2lm6fxwu08ot6.cloudfront.net/img-thumbs/960w/04LDEYRW59.jpg">Zdjęcie 1</a>
                    </li>
                    <li><a href="https://d2lm6fxwu08ot6.cloudfront.net/img-thumbs/960w/90V03Q5Y60.jpg">Zdjęcie 2</a>
                    </li>
                    <li><a href="https://d2lm6fxwu08ot6.cloudfront.net/img-thumbs/960w/O83SF2RB6D.jpg">Zdjęcie 3</a>
                    </li>
                    <li><a href="https://d2lm6fxwu08ot6.cloudfront.net/img-thumbs/960w/5JVPSVP7EI.jpg">Zdjęcie 4</a>
                    </li>
                    <li><a href="https://d2lm6fxwu08ot6.cloudfront.net/img-thumbs/960w/C5Y10KIIHA.jpg">Zdjęcie 5</a>
                    </li>
                    <li><a href="https://d2lm6fxwu08ot6.cloudfront.net/img-thumbs/960w/YSSFRY5B25.jpg">Zdjęcie 6</a>
                    </li>
                </ul>
            </ol>

        </div>

        <h1>Zdjęcia</h1>
        <div class="row">
            <div class="col-lg-4 col-6 px-0"><img
                    src="https://d2lm6fxwu08ot6.cloudfront.net/img-thumbs/960w/04LDEYRW59.jpg"
                    class="img-thumbnail"></div>
            <div class="col-lg-4 col-6 px-0"><img
                    src="https://d2lm6fxwu08ot6.cloudfront.net/img-thumbs/960w/90V03Q5Y60.jpg"
                    class="img-thumbnail"></div>
            <div class="col-lg-4 col-6 px-0"><img
                    src="https://d2lm6fxwu08ot6.cloudfront.net/img-thumbs/960w/O83SF2RB6D.jpg"
                    class="img-thumbnail"></div>

            <div class="col-lg-4 col-6 px-0"><img
                    src="https://d2lm6fxwu08ot6.cloudfront.net/img-thumbs/960w/5JVPSVP7EI.jpg"
                    class="img-thumbnail"></div>
            <div class="col-lg-4 col-6 px-0"><img
                    src="https://d2lm6fxwu08ot6.cloudfront.net/img-thumbs/960w/C5Y10KIIHA.jpg"
                    class="img-thumbnail"></div>
            <div class="col-lg-4 col-6 px-0"><img
                    src="https://d2lm6fxwu08ot6.cloudfront.net/img-thumbs/960w/YSSFRY5B25.jpg"
                    class="img-thumbnail"></div>
        </div>
    </div>
{% endblock %}

templates/lab1/register.html
{% extends "base.html" %}
{% load static %}

{% block title_block %}
    <title>Rejestracja</title>
{% endblock %}

{% block css_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/master.css' %}">
{% endblock css_block %}


{% block body_block %}
    <div class="container register-form">
        <div class="form">
            <div class="note">
                <h1 id="title">Rejestracja</h1>
            </div>

            <div class="form-content">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Imię" value=""/>
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="Emial" value=""/>
                        </div>

                        <div class="form-group">
                            <input type="password" class="form-control" placeholder="Hasło" value=""/>
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" placeholder="Potwierdź hasło" value=""/>
                        </div>
                        <div class="form-group mybutton">
                            <button type="button" class="btnSubmit">Prześlij</button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

templates/lab1/sign.html
{% extends "base.html" %}
{% load static %}

{% block css_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/master.css' %}">
{% endblock css_block %}

{% block title_block %}
    <title>Logowanie</title>
{% endblock %}

{% block body_block %}

    <br>

    <div class="container">
        <div class="jumbotron j1">
            <br>
            <h1 class="display-4">Logowanie</h1>
            <p class="lead">Wprowadź swój adres emial i hasło</p>
            <br><br><br><br><br>
        </div>

        <form>
            <div class="form-group">
                <label for="exampleInputEmail1">Email</label>
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                       placeholder="Email">
                <small id="emailHelp" class="form-text text-muted">Twój email jest w pełni chroniony.</small>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Hasło</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Hasło">
            </div>
            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Zapamiętaj mnie</label>
            </div>
            <button type="submit" class="btn btn-primary">Prześlij</button>
        </form>

    </div>
{% endblock %}

templates/lab2/animals.html
{% extends "base.html" %}
{% load static %}

{% block title_block %}
    <title>Zwierzęta</title>
{% endblock %}

{% block css_block %}
    <style>
        .jumbotron {
            background: white;
        }
    </style>
{% endblock css_block %}

{% block body_block %}
    <br>
    <div class="container">
        <div class="jumbotron" align="center">
            <div class="row">
                <div class="col-md-6">
                    <img id="bird" src="{% static "img/birdout.gif" %}">
                    <br>
                    <img id="walrus" src="{% static "img/walrusout.gif" %}">
                    <br>
                    <img id="gator" src="{% static "img/gatorover.gif" %}">
                    <br>
                    <img id="dog" src="{% static "img/dogout.gif" %}">
                    <br>
                    <img id="pig" src="{% static "img/pigout.gif" %}">
                    <br>
                    <img id="snake" src="{% static "img/snakeout.gif" %}">
                    <br>
                    <img id="reindeer" src="{% static "img/reindeerout.gif" %}">
                    <br>
                    <img id="turkey" src="{% static "img/turkeyout.gif" %}">
                    <br>
                    <img id="cow" src="{% static "img/cowout.gif" %}">
                    <br>
                    <img id="crane" src="{% static "img/craneout.gif" %}">
                </div>
                <div class="col-md-6" align="left">
                    <br>
                    <img id="picture" src="{% static "img/gator.gif" %}">
                </div>
            </div>

        </div>
    </div>
{% endblock body_block %}

{% block script %}
    <script>
        var prev = document.getElementById("gator");

        function cleanLast(){
            prev_name = prev.id+"out.gif";
            console.log(prev_name);
            prev.src = "{% static "" %}img/"+prev_name;
        }

        document.getElementById("bird").addEventListener("click", function () {
            if(this.id != prev.id){
            this.src = "{% static "img/birdover.gif" %}";
            document.getElementById("picture").src = "{% static "img/bird.gif" %}";
                   cleanLast();
            prev = this;
            }
        })

        document.getElementById("walrus").addEventListener("click", function () {
            if(this.id != prev.id){
            this.src = "{% static "img/walrusover.gif" %}";
            document.getElementById("picture").src = "{% static "img/walrus.gif" %}";
                   cleanLast();
            prev = this;
            }
        })

            document.getElementById("gator").addEventListener("click", function () {
            if(this.id != prev.id){
            this.src = "{% static "img/gatorover.gif" %}";
            document.getElementById("picture").src = "{% static "img/gator.gif" %}";
                   cleanLast();
            prev = this;
            }
        })
            document.getElementById("dog").addEventListener("click", function () {
            if(this.id != prev.id){
            this.src = "{% static "img/dogover.gif" %}";
            document.getElementById("picture").src = "{% static "img/dog.gif" %}";
                   cleanLast();
            prev = this;
            }
        })
            document.getElementById("pig").addEventListener("click", function () {
            if(this.id != prev.id){
            this.src = "{% static "img/pigover.gif" %}";
            document.getElementById("picture").src = "{% static "img/pig.gif" %}";
                   cleanLast();
            prev = this;
            }
        })
            document.getElementById("snake").addEventListener("click", function () {
            if(this.id != prev.id){
            this.src = "{% static "img/snakeover.gif" %}";
            document.getElementById("picture").src = "{% static "img/snake.gif" %}";
                   cleanLast();
            prev = this;
            }
        })
            document.getElementById("reindeer").addEventListener("click", function () {
            if(this.id != prev.id){
            this.src = "{% static "img/reindeerover.gif" %}";
            document.getElementById("picture").src = "{% static "img/reindeer.gif" %}";
                   cleanLast();
            prev = this;
            }
        })
            document.getElementById("turkey").addEventListener("click", function () {
            if(this.id != prev.id){
            this.src = "{% static "img/turkeyover.gif" %}";
            document.getElementById("picture").src = "{% static "img/turkey.gif" %}";
                   cleanLast();
            prev = this;
            }
        })
            document.getElementById("cow").addEventListener("click", function () {
            if(this.id != prev.id){
            this.src = "{% static "img/cowover.gif" %}";
            document.getElementById("picture").src = "{% static "img/cow.gif" %}";
                   cleanLast();
            prev = this;
            }
        })
            document.getElementById("crane").addEventListener("click", function () {
            if(this.id != prev.id){
            this.src = "{% static "img/craneover.gif" %}";
            document.getElementById("picture").src = "{% static "img/crane.gif" %}";
                   cleanLast();
            prev = this;
            }
        })


    </script>
{% endblock script %}

templates/lab2/animation.html
{% extends "lab2/../base.html" %}
{% load static %}

{% block title_block %}
    <title>Animacja</title>
{% endblock %}

{% block css_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/animation.css' %}">
{% endblock css_block %}

{% block body_block %}
    <br>
    <div class="container">
        <img id="animacja" src="{% static "img/rocketship.gif" %}" width="50" height="50">

        <div class="buttons" align="center">
            <button type="button" id="faster" class="btn btn-primary">Szybciej</button>
            <button type="button" id="slower" class="btn btn-primary">Wolniej</button>
        </div>
    </div>

{% endblock body_block %}

{% block script %}
    <script src="{% static "js/animation.js" %}"></script>
{% endblock script %}

templates/lab2/form.html
{% extends "lab2/../base.html" %}
{% load static %}

{% block title_block %}
    <title>Formularz</title>
{% endblock %}

{% block css_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}">
{% endblock css_block %}

{% block body_block %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="jumbotron j1">
                    <form>
                        <div class="form-row">
                            <div class="col-md-9">
                                <input type="text" class="form-control" id="imie" aria-describedby="imieHelp"
                                       placeholder="Imię">
                            </div>
                            <div class="col-md-3">
                                <small id="imieHelp" class="form-text"></small>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-md-9">
                                <input type="text" class="form-control" id="nazwisko" aria-describedby="nazwiskoHelp"
                                       placeholder="Nazwisko">
                            </div>
                            <div class="col-md-3">
                                <small id="nazwiskoHelp" class="form-text"></small>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-md-9">
                                <input type="text" class="form-control" id="telefon" aria-describedby="telefonHelp"
                                       placeholder="Numer telefonu">
                            </div>
                            <div class="col-md-3">
                                <small id="telefonHelp" class="form-text"></small>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-md-9">
                                <input type="text" class="form-control" id="data" aria-describedby="dataHelp"
                                       placeholder="Data urodzenia">
                            </div>
                            <div class="col-md-3">
                                <small id="dataHelp" class="form-text"></small>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-md-9">
                                <input type="email" class="form-control" id="email" aria-describedby="emailHelp"
                                       placeholder="Email">
                            </div>
                            <div class="col-md-3">
                                <small id="emailHelp" class="form-text"></small>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-md-9">
                                <input type="text" class="form-control" id="login" aria-describedby="loginHelp"
                                       placeholder="Login">
                            </div>
                            <div class="col-md-3">
                                <small id="loginHelp" class="form-text"></small>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-md-9">
                                <input type="password" class="form-control" id="haslo" aria-describedby="hasloHelp"
                                       placeholder="Hasło">
                            </div>
                            <div class="col-md-3">
                                <small id="hasloHelp" class="form-text"></small>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="col-md-9">
                                <input type="password" class="form-control" id="haslo_2" aria-describedby="haslo_2Help"
                                       placeholder="Powtórz hasło">
                            </div>
                            <div class="col-md-3">
                                <small id="haslo_2Help" class="form-text"></small>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-md-9">
                                <button type="button" id="myButton" class="btn btn-primary">Prześlij</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
            <div class="col-md-4">
                <div class="jumbotron j2">
                    <p id="results"></p>
                </div>

            </div>
        </div>

    </div>

{% endblock body_block %}

{% block script %}
    <script src="{% static "js/form.js" %}"></script>
{% endblock script %}

templates/lab2/game.html
{% extends "lab2/../base.html" %}
{% load static %}

{% block title_block %}
    <title>Gra zrecznościowa</title>
{% endblock %}

{% block css_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/game.css' %}">
{% endblock css_block %}

{% block body_block %}
    <p id="result">Wynik: 0</p>
    <p id="time">Odświeżenie(ms): 5000</p>
    <img id="obiekt" src="{% static "img/rocketship.gif" %}" width="50" height="50">

{% endblock body_block %}

{% block script %}
    <script>
        var width = document.body.clientWidth - 100
        var height = document.documentElement.clientHeight - 100;

        var obiekt = document.getElementById("obiekt");

        var score = 0;
        var block = false;

        var correct_img = obiekt.src

        obiekt.style.left = "1px"
        obiekt.style.top = "120px"

        //boundries
        // y >120 and y< height
        // x>0 and x< width


        myTime = 5000;

        function getRandomInt(min, max) {
            min = Math.ceil(min);
            max = Math.floor(max);

            return Math.floor(Math.random() * (max - min)) + min;
        }

        function updatePoints() {
            document.getElementById("result").textContent = "Wynik: " + score
        }

        function nextPosition() {
            x = getRandomInt(0, width);
            y = getRandomInt(120, height);
            position = {x_pos: x, y_pos: y};
            return position;
        }

        function generateWrong() {
            rand = getRandomInt(0, 100)
            return rand
        }

        function moveObject() {
            position = nextPosition()
            obiekt.style.top = position.y_pos + "px"
            obiekt.style.left = position.x_pos + "px"
            block = false
            rand = generateWrong()
            if (rand < 20) {
                obiekt.src = "{% static "img/snake.gif" %}"
            } else {
                obiekt.src = "{% static "img/rocketship.gif" %}"
            }
        }

        function updateTime() {
            if (score == 0) {
                myTime = 5000
            } else if (score == 1) {
                myTime = 4500
            } else if (score == 2) {
                myTime = 3800
            } else {
                myTime = 5000 / (Math.log2(score))
                console.log(5000 / (Math.log2(score)))
            }
        }

        obiekt.onclick = function () {
            if (block == false) {
                if (obiekt.src == correct_img) {
                    block = true;
                    score++;
                } else if (block == false && obiekt.src != correct_img) {
                    block = true;
                    score--;
                }
                updatePoints();
                updateTime();
                document.getElementById("time").textContent= "Odświeżanie(ms): "+parseInt(myTime)
            }

        }


        setTimeout(function run() {
            moveObject()
            setTimeout(run, myTime);
        }, myTime);

    </script>
{% endblock script %}

templates/lab2/picture.html
{% extends "lab2/../base.html" %}
{% load static %}

{% block title_block %}
    <title>Zmieniające sie logo</title>
{% endblock %}

{% block css_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/master.css' %}">
{% endblock css_block %}

{% block body_block %}
    <br>
    <div class="container">
        <div class="jumbotron j1" align="center">
            <a id="odnosnik" href="https://www.google.com/"><img id="icon"
                    src="https://widoczni.com/assets/blog/Od-1997-do-teraz-czyli-jak-zmienial-sie-logotyp-Google/6/LOGO-G.png" width="300" height="300"></a>
        </div>
    </div>
{% endblock body_block %}

{% block script %}
    <script src="{% static "js/picture.js" %}"></script>
{% endblock script %}

templates/lab3/snake.html
{% extends "lab2/../base.html" %}
{% load static %}

{% block title_block %}
    <title>Snake</title>
{% endblock %}

{% block css_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/snake.css' %}">
{% endblock css_block %}

{% block body_block %}
    <div class="container">
        <div class="name">
            <p id="playerName">Imię gracza: </p>
        </div>
        <div class="score">
            <p id="score">Wynik: 0</p>
        </div>
        <div class="jumbotron" align="center">
            <h2 id="h2">Gra rozpocznie się po wciśnięciu dowolnej strzałki na klawiaturze</h2>
            <div class="canvasDiv">
                <canvas id="myCanvas" class="canvasDiv" style="border:1px solid #000000;">
                </canvas>
            </div>
            <br>
            <button id="resetButton" type="button" class="btn btn-primary btn-lg">Restart!</button>
            <button id="top3Button" type="button" class="btn btn-primary btn-lg" onclick="location.href='{% url "lab3:scores" %}'">TOP 3</button>
        </div>

    </div>


{% endblock body_block %}

{% block script %}
    <script src="{% static "js/snake.js" %}"></script>
{% endblock script %}